### ISSUE TITLE
***URGENT*** | Node JS | Application Insights failing v2.1.4

### ISSUE THREAD

**Issue by smo043** [microsoft/ApplicationInsights-node.js#806]
After upgrading the Application Insights package to v2.1.4, we started seeing the below error. Can some one help:

package.json:
```
{
   "dependencies": {
      "applicationinsights": "2.1.4",
      "typescript": "^4.3.5"
   },
   "devDependencies": {
      "@types/node": "15"
   }
}
```

Local Node and npm version:
```
node: v16.2.0
npm: 7.13.0
yarn berry (3.0.0)
```

`TypeError: span.context is not a function
    at TracingPolicy.<anonymous> (/Users/XYZ/node_modules/@azure/core-http/src/policies/tracingPolicy.ts:79:32)
    at step (/Users/XYZ/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/XYZ/node_modules/tslib/tslib.js:124:57)
    at /Users/XYZ/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/XYZ/node_modules/tslib/tslib.js:113:16)
    at TracingPolicy.sendRequest (/Users/XYZ/node_modules/@azure/core-http/dist/index.js:4421:22)
    at ProxyPolicy.sendRequest (/Users/XYZ/node_modules/@azure/core-http/src/policies/proxyPolicy.ts:158:29)
    at IdentityClient.ServiceClient.sendRequest (/Users/XYZ/node_modules/@azure/core-http/src/serviceClient.ts:303:25)
    at IdentityClient.<anonymous> (/Users/XYZ/node_modules/@azure/identity/src/client/identityClient.ts:80:33)
[ERROR] 13:14:35 TypeError: span.context is not a function`

**Comment by hectorhdzg** [comment]
@smo043 can you include versions of Azure SDKs you are using as well?, looks like you are using @azure/identity, this error is caused by a mismatch of OpenTelemetry versions in your project, please ensure you are using latest of all the @azure packages

**Comment by smo043** [comment]
> @smo043 can you include versions of Azure SDKs you are using as well?, looks like you are using @azure/identity, this error is caused by a mismatch of OpenTelemetry versions in your project, please ensure you are using latest of all the @Azure packages

Gotcha thank you will try to update all package versions

**Comment by hectorhdzg** [comment]
This must be resolved in version 2.1.7
